version: '3.11'
services:
  web:
    build:
      context: .
      # dockerfile: ./
    image: rag:latest      
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "8000:8000"